# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: WolfSound
email: jan.wilczek@thewolfsound.com
author: Jan Wilczek
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to WolfSound – a "rough" blog about audio programming!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thewolfsound.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  JanWilczek
youtube_channel: https://www.youtube.com/c/WolfSoundAudio
linkedin_account: https://www.linkedin.com/in/jan-wilczek-audio-programmer/
twitter_account: https://twitter.com/wilczek_jan
facebook_page: https://www.facebook.com/JanWilczekWolfSound
logo_title_path: /wp-content/uploads/2019/10/LogoNameOnly.png
google_analytics: UA-149437803-2

# Build settings
theme: jekyll-theme-clean-blog
markdown:           kramdown
kramdown:
  math_engine: mathjax
  auto_ids: true
permalink: /:categories/:title/
highlighter: rouge
pagination:
  enabled: true
  per_page: 5
  permalink: "/posts/page:num/"
future: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-katex
  
katex:
  js_path: "assets/js/katex/" # Path used to search for katex.min.js
  rendering_options:
    # Default KaTeX rendering options. See https://github.com/Khan/KaTeX#rendering-options
    throw_error: true                       # throwOnError - set to false if you want rendering to output error as text rather than a build error
    error_color: "#cc0000"                  # errorColor

talkyard_server_url: https://comments-for-www-thewolfsound-com.talkyard.net
talkyard_script_url: https://c1.ty-cdn.net/-/talkyard-comments.min.js

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# User data
collections:
  authors:
    output: true

defaults:
#   - scope:
#      path: ""
#      type: "authors"
#     values:
#      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
#   - scope:
#       path: ""
#     values:
#       layout: "default"

